// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_stats.proto

#ifndef PROTOBUF_pb_5fstats_2eproto__INCLUDED
#define PROTOBUF_pb_5fstats_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb_stats {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pb_5fstats_2eproto();
void protobuf_AssignDesc_pb_5fstats_2eproto();
void protobuf_ShutdownFile_pb_5fstats_2eproto();

class StatEntry;
class Stats;

// ===================================================================

class StatEntry : public ::google::protobuf::Message {
 public:
  StatEntry();
  virtual ~StatEntry();

  StatEntry(const StatEntry& from);

  inline StatEntry& operator=(const StatEntry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StatEntry& default_instance();

  void Swap(StatEntry* other);

  // implements Message ----------------------------------------------

  StatEntry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StatEntry& from);
  void MergeFrom(const StatEntry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes host = 1;
  inline bool has_host() const;
  inline void clear_host();
  static const int kHostFieldNumber = 1;
  inline const ::std::string& host() const;
  inline void set_host(const ::std::string& value);
  inline void set_host(const char* value);
  inline void set_host(const void* value, size_t size);
  inline ::std::string* mutable_host();
  inline ::std::string* release_host();
  inline void set_allocated_host(::std::string* host);

  // required int64 bytes_hit = 2;
  inline bool has_bytes_hit() const;
  inline void clear_bytes_hit();
  static const int kBytesHitFieldNumber = 2;
  inline ::google::protobuf::int64 bytes_hit() const;
  inline void set_bytes_hit(::google::protobuf::int64 value);

  // required int64 bytes_miss = 3;
  inline bool has_bytes_miss() const;
  inline void clear_bytes_miss();
  static const int kBytesMissFieldNumber = 3;
  inline ::google::protobuf::int64 bytes_miss() const;
  inline void set_bytes_miss(::google::protobuf::int64 value);

  // required int32 reqs_hit = 4;
  inline bool has_reqs_hit() const;
  inline void clear_reqs_hit();
  static const int kReqsHitFieldNumber = 4;
  inline ::google::protobuf::int32 reqs_hit() const;
  inline void set_reqs_hit(::google::protobuf::int32 value);

  // required int32 reqs_miss = 5;
  inline bool has_reqs_miss() const;
  inline void clear_reqs_miss();
  static const int kReqsMissFieldNumber = 5;
  inline ::google::protobuf::int32 reqs_miss() const;
  inline void set_reqs_miss(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pb_stats.StatEntry)
 private:
  inline void set_has_host();
  inline void clear_has_host();
  inline void set_has_bytes_hit();
  inline void clear_has_bytes_hit();
  inline void set_has_bytes_miss();
  inline void clear_has_bytes_miss();
  inline void set_has_reqs_hit();
  inline void clear_has_reqs_hit();
  inline void set_has_reqs_miss();
  inline void clear_has_reqs_miss();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* host_;
  ::google::protobuf::int64 bytes_hit_;
  ::google::protobuf::int64 bytes_miss_;
  ::google::protobuf::int32 reqs_hit_;
  ::google::protobuf::int32 reqs_miss_;
  friend void  protobuf_AddDesc_pb_5fstats_2eproto();
  friend void protobuf_AssignDesc_pb_5fstats_2eproto();
  friend void protobuf_ShutdownFile_pb_5fstats_2eproto();

  void InitAsDefaultInstance();
  static StatEntry* default_instance_;
};
// -------------------------------------------------------------------

class Stats : public ::google::protobuf::Message {
 public:
  Stats();
  virtual ~Stats();

  Stats(const Stats& from);

  inline Stats& operator=(const Stats& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stats& default_instance();

  void Swap(Stats* other);

  // implements Message ----------------------------------------------

  Stats* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stats& from);
  void MergeFrom(const Stats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pb_stats.StatEntry data = 1;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::pb_stats::StatEntry& data(int index) const;
  inline ::pb_stats::StatEntry* mutable_data(int index);
  inline ::pb_stats::StatEntry* add_data();
  inline const ::google::protobuf::RepeatedPtrField< ::pb_stats::StatEntry >&
      data() const;
  inline ::google::protobuf::RepeatedPtrField< ::pb_stats::StatEntry >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:pb_stats.Stats)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pb_stats::StatEntry > data_;
  friend void  protobuf_AddDesc_pb_5fstats_2eproto();
  friend void protobuf_AssignDesc_pb_5fstats_2eproto();
  friend void protobuf_ShutdownFile_pb_5fstats_2eproto();

  void InitAsDefaultInstance();
  static Stats* default_instance_;
};
// ===================================================================


// ===================================================================

// StatEntry

// required bytes host = 1;
inline bool StatEntry::has_host() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StatEntry::set_has_host() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StatEntry::clear_has_host() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StatEntry::clear_host() {
  if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_->clear();
  }
  clear_has_host();
}
inline const ::std::string& StatEntry::host() const {
  // @@protoc_insertion_point(field_get:pb_stats.StatEntry.host)
  return *host_;
}
inline void StatEntry::set_host(const ::std::string& value) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(value);
  // @@protoc_insertion_point(field_set:pb_stats.StatEntry.host)
}
inline void StatEntry::set_host(const char* value) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(value);
  // @@protoc_insertion_point(field_set_char:pb_stats.StatEntry.host)
}
inline void StatEntry::set_host(const void* value, size_t size) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:pb_stats.StatEntry.host)
}
inline ::std::string* StatEntry::mutable_host() {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:pb_stats.StatEntry.host)
  return host_;
}
inline ::std::string* StatEntry::release_host() {
  clear_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = host_;
    host_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void StatEntry::set_allocated_host(::std::string* host) {
  if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete host_;
  }
  if (host) {
    set_has_host();
    host_ = host;
  } else {
    clear_has_host();
    host_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:pb_stats.StatEntry.host)
}

// required int64 bytes_hit = 2;
inline bool StatEntry::has_bytes_hit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StatEntry::set_has_bytes_hit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StatEntry::clear_has_bytes_hit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StatEntry::clear_bytes_hit() {
  bytes_hit_ = GOOGLE_LONGLONG(0);
  clear_has_bytes_hit();
}
inline ::google::protobuf::int64 StatEntry::bytes_hit() const {
  // @@protoc_insertion_point(field_get:pb_stats.StatEntry.bytes_hit)
  return bytes_hit_;
}
inline void StatEntry::set_bytes_hit(::google::protobuf::int64 value) {
  set_has_bytes_hit();
  bytes_hit_ = value;
  // @@protoc_insertion_point(field_set:pb_stats.StatEntry.bytes_hit)
}

// required int64 bytes_miss = 3;
inline bool StatEntry::has_bytes_miss() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StatEntry::set_has_bytes_miss() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StatEntry::clear_has_bytes_miss() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StatEntry::clear_bytes_miss() {
  bytes_miss_ = GOOGLE_LONGLONG(0);
  clear_has_bytes_miss();
}
inline ::google::protobuf::int64 StatEntry::bytes_miss() const {
  // @@protoc_insertion_point(field_get:pb_stats.StatEntry.bytes_miss)
  return bytes_miss_;
}
inline void StatEntry::set_bytes_miss(::google::protobuf::int64 value) {
  set_has_bytes_miss();
  bytes_miss_ = value;
  // @@protoc_insertion_point(field_set:pb_stats.StatEntry.bytes_miss)
}

// required int32 reqs_hit = 4;
inline bool StatEntry::has_reqs_hit() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void StatEntry::set_has_reqs_hit() {
  _has_bits_[0] |= 0x00000008u;
}
inline void StatEntry::clear_has_reqs_hit() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void StatEntry::clear_reqs_hit() {
  reqs_hit_ = 0;
  clear_has_reqs_hit();
}
inline ::google::protobuf::int32 StatEntry::reqs_hit() const {
  // @@protoc_insertion_point(field_get:pb_stats.StatEntry.reqs_hit)
  return reqs_hit_;
}
inline void StatEntry::set_reqs_hit(::google::protobuf::int32 value) {
  set_has_reqs_hit();
  reqs_hit_ = value;
  // @@protoc_insertion_point(field_set:pb_stats.StatEntry.reqs_hit)
}

// required int32 reqs_miss = 5;
inline bool StatEntry::has_reqs_miss() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void StatEntry::set_has_reqs_miss() {
  _has_bits_[0] |= 0x00000010u;
}
inline void StatEntry::clear_has_reqs_miss() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void StatEntry::clear_reqs_miss() {
  reqs_miss_ = 0;
  clear_has_reqs_miss();
}
inline ::google::protobuf::int32 StatEntry::reqs_miss() const {
  // @@protoc_insertion_point(field_get:pb_stats.StatEntry.reqs_miss)
  return reqs_miss_;
}
inline void StatEntry::set_reqs_miss(::google::protobuf::int32 value) {
  set_has_reqs_miss();
  reqs_miss_ = value;
  // @@protoc_insertion_point(field_set:pb_stats.StatEntry.reqs_miss)
}

// -------------------------------------------------------------------

// Stats

// repeated .pb_stats.StatEntry data = 1;
inline int Stats::data_size() const {
  return data_.size();
}
inline void Stats::clear_data() {
  data_.Clear();
}
inline const ::pb_stats::StatEntry& Stats::data(int index) const {
  // @@protoc_insertion_point(field_get:pb_stats.Stats.data)
  return data_.Get(index);
}
inline ::pb_stats::StatEntry* Stats::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:pb_stats.Stats.data)
  return data_.Mutable(index);
}
inline ::pb_stats::StatEntry* Stats::add_data() {
  // @@protoc_insertion_point(field_add:pb_stats.Stats.data)
  return data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::pb_stats::StatEntry >&
Stats::data() const {
  // @@protoc_insertion_point(field_list:pb_stats.Stats.data)
  return data_;
}
inline ::google::protobuf::RepeatedPtrField< ::pb_stats::StatEntry >*
Stats::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:pb_stats.Stats.data)
  return &data_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb_stats

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pb_5fstats_2eproto__INCLUDED
