
JEMALLOC_VER=4.3.1
JEMALLOC_DIR=jemalloc-${JEMALLOC_VER}
JEMALLOC_INSTALL_DIR=inst_dir
JEMALLOC_INCLUDE_DIR=${JEMALLOC_DIR}/${JEMALLOC_INSTALL_DIR}/include
JEMALLOC_LIB_DIR=${JEMALLOC_DIR}/${JEMALLOC_INSTALL_DIR}/lib
